# Form implementation generated from reading ui file 'gui/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, -20, 551, 561))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.textMachines = QtWidgets.QTextEdit(parent=self.tab_1)
        self.textMachines.setGeometry(QtCore.QRect(10, 10, 361, 331))
        self.textMachines.setObjectName("textMachines")
        self.textProduits = QtWidgets.QTextEdit(parent=self.tab_1)
        self.textProduits.setGeometry(QtCore.QRect(380, 10, 161, 151))
        self.textProduits.setObjectName("textProduits")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.tab_1)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 350, 441, 131))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.nomLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.nomLabel.setObjectName("nomLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.nomLabel)
        self.inputNom = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.inputNom.setObjectName("inputNom")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inputNom)
        self.puissanceLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.puissanceLabel.setObjectName("puissanceLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.puissanceLabel)
        self.inputPuissance = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.inputPuissance.setObjectName("inputPuissance")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inputPuissance)
        self.opRateurLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.opRateurLabel.setObjectName("opRateurLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.opRateurLabel)
        self.inputOprateur = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.inputOprateur.setObjectName("inputOprateur")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inputOprateur)
        self.emailLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.emailLabel.setObjectName("emailLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.emailLabel)
        self.inputEmail = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.inputEmail.setObjectName("inputEmail")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inputEmail)
        self.btnAddMachine = QtWidgets.QPushButton(parent=self.tab_1)
        self.btnAddMachine.setGeometry(QtCore.QRect(0, 490, 121, 26))
        self.btnAddMachine.setObjectName("btnAddMachine")
        self.btnRefresh = QtWidgets.QPushButton(parent=self.tab_1)
        self.btnRefresh.setGeometry(QtCore.QRect(340, 490, 81, 26))
        self.btnRefresh.setObjectName("btnRefresh")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textMachines.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Machines</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textProduits.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Produits</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.nomLabel.setText(_translate("MainWindow", "Nom"))
        self.puissanceLabel.setText(_translate("MainWindow", "Puissance"))
        self.opRateurLabel.setText(_translate("MainWindow", "Opérateur"))
        self.emailLabel.setText(_translate("MainWindow", "Email"))
        self.btnAddMachine.setText(_translate("MainWindow", "Ajouter machine"))
        self.btnRefresh.setText(_translate("MainWindow", "Rafraichir"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Configuration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Commandes"))
