# Form implementation generated from reading ui file 'gui/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1029, 655)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(90, 0, 861, 601))
        self.tabWidget.setObjectName("tabWidget")
        self.Configuration = QtWidgets.QWidget()
        self.Configuration.setObjectName("Configuration")
        self.textMachines = QtWidgets.QTextEdit(parent=self.Configuration)
        self.textMachines.setGeometry(QtCore.QRect(10, 10, 361, 331))
        self.textMachines.setObjectName("textMachines")
        self.textProduits = QtWidgets.QTextEdit(parent=self.Configuration)
        self.textProduits.setGeometry(QtCore.QRect(380, 10, 161, 151))
        self.textProduits.setObjectName("textProduits")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.Configuration)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 350, 441, 138))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.inputNom = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.inputNom.setObjectName("inputNom")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inputNom)
        self.puissanceLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.puissanceLabel.setObjectName("puissanceLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.puissanceLabel)
        self.inputPuissance = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.inputPuissance.setObjectName("inputPuissance")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inputPuissance)
        self.opRateurLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.opRateurLabel.setObjectName("opRateurLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.opRateurLabel)
        self.inputOperateur = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.inputOperateur.setObjectName("inputOperateur")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inputOperateur)
        self.emailLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.emailLabel.setObjectName("emailLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.emailLabel)
        self.inputEmail = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.inputEmail.setObjectName("inputEmail")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inputEmail)
        self.nomLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.nomLabel.setObjectName("nomLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.nomLabel)
        self.btnAddMachine = QtWidgets.QPushButton(parent=self.Configuration)
        self.btnAddMachine.setGeometry(QtCore.QRect(0, 490, 121, 26))
        self.btnAddMachine.setObjectName("btnAddMachine")
        self.btnRefresh = QtWidgets.QPushButton(parent=self.Configuration)
        self.btnRefresh.setGeometry(QtCore.QRect(340, 490, 81, 26))
        self.btnRefresh.setObjectName("btnRefresh")
        self.tabWidget.addTab(self.Configuration, "")
        self.Commandes = QtWidgets.QWidget()
        self.Commandes.setObjectName("Commandes")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Commandes)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.Commandes)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboProduit = QtWidgets.QComboBox(parent=self.Commandes)
        self.comboProduit.setObjectName("comboProduit")
        self.verticalLayout.addWidget(self.comboProduit)
        self.label_2 = QtWidgets.QLabel(parent=self.Commandes)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.inputQuantite = QtWidgets.QLineEdit(parent=self.Commandes)
        self.inputQuantite.setObjectName("inputQuantite")
        self.verticalLayout.addWidget(self.inputQuantite)
        self.label_3 = QtWidgets.QLabel(parent=self.Commandes)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.inputHeureDepart = QtWidgets.QLineEdit(parent=self.Commandes)
        self.inputHeureDepart.setObjectName("inputHeureDepart")
        self.verticalLayout.addWidget(self.inputHeureDepart)
        self.btnAddCommande = QtWidgets.QPushButton(parent=self.Commandes)
        self.btnAddCommande.setObjectName("btnAddCommande")
        self.verticalLayout.addWidget(self.btnAddCommande)
        self.textCommandes = QtWidgets.QTextEdit(parent=self.Commandes)
        self.textCommandes.setObjectName("textCommandes")
        self.verticalLayout.addWidget(self.textCommandes)
        self.tabWidget.addTab(self.Commandes, "")
        self.PrixElectricite = QtWidgets.QWidget()
        self.PrixElectricite.setObjectName("PrixElectricite")
        self.pushButtonPrices = QtWidgets.QPushButton(parent=self.PrixElectricite)
        self.pushButtonPrices.setGeometry(QtCore.QRect(110, 100, 80, 24))
        self.pushButtonPrices.setObjectName("pushButtonPrices")
        self.tabWidget.addTab(self.PrixElectricite, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1029, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textMachines.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Machines</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textProduits.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Produits</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.puissanceLabel.setText(_translate("MainWindow", "Puissance"))
        self.opRateurLabel.setText(_translate("MainWindow", "Opérateur"))
        self.emailLabel.setText(_translate("MainWindow", "Email"))
        self.nomLabel.setText(_translate("MainWindow", "Nom"))
        self.btnAddMachine.setText(_translate("MainWindow", "Ajouter machine"))
        self.btnRefresh.setText(_translate("MainWindow", "Rafraichir"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Configuration), _translate("MainWindow", "Configuration"))
        self.label.setText(_translate("MainWindow", "Produit"))
        self.label_2.setText(_translate("MainWindow", "Quantité"))
        self.label_3.setText(_translate("MainWindow", "Heure de départ"))
        self.btnAddCommande.setText(_translate("MainWindow", "Ajouter commande"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Commandes), _translate("MainWindow", "Commandes"))
        self.pushButtonPrices.setText(_translate("MainWindow", "Afficher prix"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PrixElectricite), _translate("MainWindow", "Page"))
